p8131\_hw8\_xy2395
================
Jack Yan
4/18/2019

``` r
library(tidyverse)
library(readxl)
library(gee)
library(lme4)
health_df = read_xlsx('../hw8/HW8-HEALTH.xlsx')
```

``` r
# Data manipulation
health_df <-
  health_df %>% 
  janitor::clean_names()
```

### (a)

``` r
# Use baseline data only
health_baseline <-
  health_df %>%
  filter(time == 1)

# 2-way table
table(health_baseline$txt, health_baseline$health) %>% 
  addmargins()  %>% 
  knitr::kable()
```

|              |  Good|  Poor|  Sum|
|--------------|-----:|-----:|----:|
| Control      |    20|    21|   41|
| Intervention |    16|    23|   39|
| Sum          |    36|    44|   80|

``` r
# expected values
table(health_baseline$txt, health_baseline$health) %>% 
  chisq.test() %>% .$expected
```

    ##               
    ##                 Good  Poor
    ##   Control      18.45 22.55
    ##   Intervention 17.55 21.45

``` r
# chi-squared test for association between assignment and health rating
table(health_baseline$txt, health_baseline$health) %>% 
  chisq.test()
```

    ## 
    ##  Pearson's Chi-squared test with Yates' continuity correction
    ## 
    ## data:  .
    ## X-squared = 0.22287, df = 1, p-value = 0.6369

We can see from the 2-way table that the number of people randomized to control group who rated their health status as 'Good' is 20, while its expected value is 18.45. The difference between observed and expected values is acceptable. The chi-squared test (p-value = 0.6369 &gt;0.05) also suggests that evidence is not strong enough to conclude association between treatment group and health status at baseline.

### (b) GEE

``` r
health_new = 
  health_baseline %>% 
  rename(baseline = health) %>% 
  select(id, baseline) %>% 
  inner_join(., health_df, by = 'id') %>% 
  filter(time != 1) %>% 
  mutate(months = 3 * (time - 1),
         months = if_else(months == 9, 12, months),
         health = if_else(health == 'Good', 1, 0),
         baseline = fct_relevel(baseline, 'Poor'))

fit_gee = 
  gee(health ~ baseline + txt + months + agegroup,
      id = id, scale.fix = TRUE, scale.value = 1,
      family = binomial,
      corstr = 'unstructured',
      data = health_new)
```

    ## Beginning Cgee S-function, @(#) geeformula.q 4.13 98/01/27

    ## running glm to get initial regression estimate

    ##     (Intercept)    baselineGood txtIntervention          months 
    ##     -1.52535766      1.71063852      1.99669985      0.02536275 
    ##   agegroup25-34     agegroup35+ 
    ##      1.19749448      1.39742621

``` r
summary(fit_gee)
```

    ## 
    ##  GEE:  GENERALIZED LINEAR MODELS FOR DEPENDENT DATA
    ##  gee S-function, version 4.13 modified 98/01/27 (1998) 
    ## 
    ## Model:
    ##  Link:                      Logit 
    ##  Variance to Mean Relation: Binomial 
    ##  Correlation Structure:     Unstructured 
    ## 
    ## Call:
    ## gee(formula = health ~ baseline + txt + months + agegroup, id = id, 
    ##     data = health_new, family = binomial, corstr = "unstructured", 
    ##     scale.fix = TRUE, scale.value = 1)
    ## 
    ## Summary of Residuals:
    ##         Min          1Q      Median          3Q         Max 
    ## -0.98144969 -0.18317233  0.08914345  0.17159228  0.83093959 
    ## 
    ## 
    ## Coefficients:
    ##                    Estimate Naive S.E.    Naive z Robust S.E.   Robust z
    ## (Intercept)     -1.68960132 0.49985657 -3.3801723  0.52303338 -3.2303891
    ## baselineGood     1.81418056 0.48958528  3.7055456  0.50961334  3.5599158
    ## txtIntervention  2.10225898 0.48779381  4.3097286  0.53777951  3.9091467
    ## months           0.03243343 0.03665686  0.8847848  0.04755408  0.6820326
    ## agegroup25-34    1.35250468 0.48130172  2.8100973  0.50420159  2.6824681
    ## agegroup35+      1.42052166 0.79781620  1.7805124  0.78372968  1.8125148
    ## 
    ## Estimated Scale Parameter:  1
    ## Number of Iterations:  5
    ## 
    ## Working Correlation
    ##           [,1]      [,2]      [,3]
    ## [1,] 1.0000000 0.1719328 0.5859907
    ## [2,] 0.1719328 1.0000000 0.2013998
    ## [3,] 0.5859907 0.2013998 1.0000000

### (c) GLMM

``` r
fit_glmm = 
  glmer(health ~ baseline + txt + months + agegroup + (1 | id),
        data = health_new,
        family = binomial)
summary(fit_glmm)
```

    ## Generalized linear mixed model fit by maximum likelihood (Laplace
    ##   Approximation) [glmerMod]
    ##  Family: binomial  ( logit )
    ## Formula: health ~ baseline + txt + months + agegroup + (1 | id)
    ##    Data: health_new
    ## 
    ##      AIC      BIC   logLik deviance df.resid 
    ##    185.0    208.0    -85.5    171.0      192 
    ## 
    ## Scaled residuals: 
    ##     Min      1Q  Median      3Q     Max 
    ## -2.6112 -0.2327  0.1402  0.2982  1.8239 
    ## 
    ## Random effects:
    ##  Groups Name        Variance Std.Dev.
    ##  id     (Intercept) 5.721    2.392   
    ## Number of obs: 199, groups:  id, 78
    ## 
    ## Fixed effects:
    ##                 Estimate Std. Error z value Pr(>|z|)   
    ## (Intercept)     -2.58087    1.04177  -2.477  0.01323 * 
    ## baselineGood     2.77609    0.98380   2.822  0.00478 **
    ## txtIntervention  3.41322    1.07266   3.182  0.00146 **
    ## months           0.03718    0.06933   0.536  0.59178   
    ## agegroup25-34    2.25652    1.00877   2.237  0.02529 * 
    ## agegroup35+      1.98229    1.38117   1.435  0.15122   
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Correlation of Fixed Effects:
    ##             (Intr) bslnGd txtInt months a25-34
    ## baselineGod -0.632                            
    ## txtIntrvntn -0.637  0.449                     
    ## months      -0.409  0.016  0.047              
    ## agegrp25-34 -0.624  0.379  0.395  0.007       
    ## agegroup35+ -0.422  0.274  0.206 -0.007  0.390
