---
title: "p8131_hw9_xy2395"
author: "Jack Yan"
date: "4/23/2019"
output: pdf_document
---

```{r setup, include=TRUE, message=F, warning=F}
library(tidyverse)
library(KMsurv) # data source
library(survival) # problem 3
```

### Problem 3
```{r}
data(tongue)
tongue_df = 
  tongue %>% as.tibble() %>% 
  mutate(type = if_else(type == 1, "Aneuploid", "Diploid"))
```

```{r}
# Aneuploid K-M curve
KM1 = survfit(Surv(time,delta)~1, data = subset(tongue_df, type == "Aneuploid"), conf.type = 'log')
plot(KM1, 
     conf.int = TRUE, mark.time = TRUE, 
     xlab = "Weeks", ylab = "Survival Probability", main="Aneuploid K-M curve", 
     cex.lab = 1.5, cex.main = 1.5)

# Diploid K-M curve
KM2 = survfit(Surv(time,delta)~1, data = subset(tongue_df, type == "Diploid"), conf.type = 'log')
plot(KM2, 
     conf.int = TRUE, mark.time = TRUE, 
     xlab = "Weeks", ylab = "Survival Probability", main="Diploid K-M curve", 
     cex.lab = 1.5, cex.main = 1.5)
``` 

```{r}
# one-year survival rate
# Aneuploid
summary(KM1, time = 365/7)
# Diploid
summary(KM2, time = 365/7)
```

The estimated 1-year survival rate (95% CI) is 0.654 (0.537, 0.797) for Aneuploid and 0.486 (0.33, 0.716) for Diploid. 
