P8131\_hw5\_xy2395
================
Jack Yan
3/5/2019

Problem 1
---------

``` r
crab_df = 
  read.table("./hw5/HW5-crab.txt", header = TRUE) %>% 
  as.tibble()
```

### (a)

M1 : Sa ~ W

``` r
fit1 = glm(Sa ~ W, family = poisson, data = crab_df)

fit1 %>% 
  broom::tidy() %>% 
  mutate(exp_estimate = exp(estimate)) %>% 
  select(-std.error, -statistic, -p.value) %>% 
  knitr::kable()
```

| term        |    estimate|  exp\_estimate|
|:------------|-----------:|--------------:|
| (Intercept) |  -3.3047572|      0.0367081|
| W           |   0.1640451|      1.1782674|

``` r
# Deviance and Pearson statistics are similar
D = sum(residuals(fit1, type = 'deviance')^2); D
```

    ## [1] 567.8786

``` r
G = sum(residuals(fit1, type = 'pearson')^2); G
```

    ## [1] 544.157

``` r
1 - pchisq(G, df = fit1$df.residual) # df = 171
```

    ## [1] 0

The p-value is lower than 0.05, and the deviance from the full model is too large, so the fit is not good.

**Interpretation**: The estimated coefficient of W (carapace width) is 0.164. exp(0.164) = 1.18. This means the number of satellites is estimated to increase by 1.18 folds with one-unit increase in carapace width.

### (b)

M2: Sa ~ W + Wt

``` r
fit2 = glm(Sa ~ W + Wt, family = poisson, data = crab_df)

fit2 %>% 
  broom::tidy() %>% 
  mutate(exp_estimate = exp(estimate)) %>% 
  select(term, estimate, exp_estimate, p.value) %>% 
  knitr::kable()
```

| term        |    estimate|  exp\_estimate|    p.value|
|:------------|-----------:|--------------:|----------:|
| (Intercept) |  -1.2916790|       0.274809|  0.1509076|
| W           |   0.0458980|       1.046968|  0.3264035|
| Wt          |   0.4474357|       1.564296|  0.0047949|

``` r
test.stat = fit1$deviance - fit2$deviance
df = fit1$df.residual - fit2$df.residual
1 - pchisq(test.stat, df = df) # df = 1
```

    ## [1] 0.004694838

The p-value is smaller than 0.05, so we reject the null hypothesis and conclude that the larger model (M2) is superior to the smaller model (M1).

### (c)

Check Over Dispersion.

``` r
resid = residuals(fit2, type = 'pearson')
phi = sum(resid^2) / fit2$df.residual
phi
```

    ## [1] 3.156449

``` r
n = fit2$df.null + 1
plot(qnorm((n + 1:n + 0.5)/(2*n + 1.125)), sort(abs(resid)),
     xlab = 'Expected Half-Normal Order Stats',
     ylab = 'Ordered Abs Pearson Residuals')
abline(a = 0, b = 1)
abline(a = 0, b = sqrt(phi), lty = 2)
```

![](p8131_hw5_xy2395_files/figure-markdown_github/unnamed-chunk-6-1.png)

``` r
summary(fit2, dispersion = phi)$coef %>%
  broom::tidy() %>% 
  mutate(exp_estimate = exp(Estimate)) %>% 
  select(.rownames, Estimate, exp_estimate) %>%
  knitr::kable()
```

| .rownames   |    Estimate|  exp\_estimate|
|:------------|-----------:|--------------:|
| (Intercept) |  -1.2916790|       0.274809|
| W           |   0.0458980|       1.046968|
| Wt          |   0.4474357|       1.564296|

As shown in the plot, there is over-dispersion in Model 2.

**Interpretation**: The number of satellites is estimated to increase by 1.05 folds with one-unit increase in female crab's carapace width. The number of satellites is estimated to increase by 1.56 folds with one-unit increase in female crab's weight.

Problem 2
---------

``` r
parasite_df = 
  read.table("./HW5-parasite.txt", header = TRUE) %>% 
  as.tibble()
```
